config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"

  get "/users", to: "users#index", as: "users"

  get "/users/new", to: "users#new", as: "new_user"

  post "/users", to: "users#create"

  get "/users/:id", to: "users#show"

  get "/sign_in", to: "sessions#new"

  post "/sessions", to: "sessions#create"

  get "/sessions", to: "sessions#destroy", as: "user_logout"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	def self.confirm(params)
		@user = User.find_by({username: params[:username]})
		@user.try(:authenticate, params[:password])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  before_action :set_cache_buster

	def set_cache_buster
	   response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
	   response.headers["Pragma"] = "no-cache"
	   response.headers["Expires"] = "0"
	end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
		render :new
	end

	def create
		user_params = params.require(:user).permit(:username, :password)
		@user = User.confirm(user_params)
		if @user
			login(@user)
			redirect_to "/users/#{@user.id}"
		else
			redirect_to "/"
		end
	end

	def show
		render :show
	end

    def destroy
    	logout
    	set_cache_buster
    	redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in?, only: [:show]
	before_action :set_user, only: [:index, :destroy]

	def index
		@user = User.new
		render :new
	end

	def new
		@user = User.new 
		render :new
	end

	def create
		user_params = params.require(:user).permit(:username, :password, :password_confirmation)
		@user = User.new(user_params)
		if @user.save
			login(@user)
			redirect_to "/users/#{@user.id}"
		else
			redirect_to root_path
			flash[:notice] = @user.errors.full_messages.to_sentence
		end	
	end

	def show
		@user = User.find(params[:id])
		render :show
	end

	def destroy
		@user.destroy()
		logout
		redirect_to root_path
	end

	private

	def set_user
		@user = current_user
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by(session[:user_id])
	end

	def logged_in?
		if current_user == nil
			redirect_to "/sign_in"
		end	
	end

	def logout
		@current_user = session[:user_id] = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConstructionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<!-- modal for Sign Up -->	
<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                 <h2 class="modal-title" id="myModalLabel">Sign Up</h2>
            </div>
            <div class="modal-body">
                    <%= form_for @user do |f| %>
    			<div>
    				<%= f.text_field :username, placeholder: "Username" %>
    			</div>
    			<div>
    				<%= f.password_field :password, placeholder: "Password" %>
    			</div>	
    			<div>
    				<%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
    			</div>
    			<div class="modal-footer">
                    <%= f.submit "Sign Up" %>
                </div>
                    <% end %>
            </div>
        </div>
    </div>
</div>

<!-- Modal for Login -->
<!-- Delete this if modal works again -->
<div class="modal fade" id="basicModalTwo" tabindex="-1" role="dialog" aria-labelledby="basicModalTwo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                <h2 class="modal-title" id="myModalLabel">Login</h2>
            </div>
            <div class="modal-body">
                    <%= form_for @user, url: "/sessions", method: "post" do |f| %>
                <div>
                    <%= f.text_field :username, placeholder: "Username" %>
                </div>
                <div>
                    <%= f.password_field :password, placeholder: "Password" %>
                </div>  
                <div class="modal-footer">
                   <%= f.submit "Login" %>
                </div>
                   <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/_navbar.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Current Jobs <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <a href="#vegasStrip">Vegas Strip</a>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Past Jobs <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <a href="#scHouse">Cornelia's House</a>
    </ul>
  </li> 
  <li role="presentation">
    <ul class="nav nav-pills">
    <% if current_user %>  
    <li role="presentation"><%= link_to "Log Out", user_logout_path %></li>
    <% end %>
    </ul>
  </li>
</ul>

app/views/users/index.html.erb
Sign Up

<%= form_for @user do |f| %>
	<div>
		<%= f.text_field :username, placeholder: "Username" %>
	</div>
	<div>
		<%= f.password_field :password, placeholder: "Password" %>
	</div>	
	<div>
		<%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
	</div>	
	<%= f.submit "Submit" %>
<% end %>

Sign In

<%= form_for @user, url: "/sessions", method: "post" do |f| %>
	<div>
		<%= f.text_field :username, placeholder: "Username" %>
	</div>
	<div>
		<%= f.password_field :password, placeholder: "Password" %>
	</div>
	<%= f.submit "Sign In" %>
<% end %>

app/views/users/new.html.erb
<!-- Modals form -->
<%= render partial: "users/form" %>	

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<body>
<!-- Buttons on top of hero image -->
<div id="heroImage">
	<div class="container">
		<div class="row">
			<h1 id="title">Palm Landscaping Services</h1>
			<div class="row">
				<button id="basicModalOne" data-toggle="modal" data-target="#basicModal">
					Sign Up
				</button>	
				<button id="basicModalTwo" data-toggle="modal" data-target="#basicModalTwo">
					Login
				</button>
			</div>	
		</div>
	</div>
</div>

<!-- Services Offered Section -->
<div class="container" id="services">			
		<div class="row" id="servicesOffered">
			<h1>Services Offered</h1>
		</div>
		<div class="row" id="fourServices">
				<div class="col-xs-3" id="plantTrimmer">
					<img src="http://i.imgur.com/OlbT92D.jpg?1">
					<h5>Plant Trimming</h5>
				</div>
				<div class="col-xs-3">
					<img src="http://i.imgur.com/lHeQtXr.jpg">
					<h5>Leaf and Garbage Pickup</h5>	
				</div>
				<div class="col-xs-3">
					<img src="http://i.imgur.com/J6VzKMd.jpg">
					<h5>Dead Plant Replacement</h5>
				</div>
				<div class="col-xs-3">
					<img src="http://i.imgur.com/xSJ8N2T.png">
					<h5>Weed Spraying</h5>
				</div>	
		</div>			
	</div>
</div>	

<!-- Client Testimonials Section -->
<div class="container-fluid" id="testimonials">
	<div class="row" id="testimonialsTitle">
			<h1>Client Testimonials</h1>
	</div>	
	<div class="container" id="fourTestimonials">
		<div class="row">
			<div class="col-xs-6" id="firstColumn">
				<div class="col-xs-4">
					<img id="picOne" src="http://i.imgur.com/DsHjYDy.jpg">
				</div>
				<div class="col-xs-8">
					<div class="panel panel-default">
						<div class="panel-body">
							<h6 id="reviews">Spencer - Client since 2006</h6>
							<p>Bob has done great work for me since 2006.  I can't imagine going to anyone else for help.</p>
						</div>
					</div>		
				</div>
			</div>	
			<div class="col-xs-6" id="secondColumn">
				<div class="col-xs-8">	
					<div class="panel panel-default">
						<div class="panel-body">
							<h6 id="reviews">Jimmy - Client since 2013</h6>
							<p>Bob came through in the clutch after me and the boys got tired of doing our yardwork.  Completely professional, on time, and respectful.  I can see this company doing big things.</p>
						</div>
					</div>
				</div>	
				<div class="col-xs-4">
					<img id="picOne" src="http://i.imgur.com/zsxzFef.jpg">		
				</div>
			</div>		
		</div>
		<div class="row">
				<div class="col-xs-6" id="firstColumn">
					<div class="col-xs-4">
						<img id="picOne" src="http://i.imgur.com/JeGSbUF.jpg">
					</div>
					<div class="col-xs-8">
						<div class="panel panel-default">
							<div class="panel-body">
								<h6 id="reviews">Erika - Client since 2015</h6>
								<p>While on a cruise to the Bahamas, I realized that I desperately needed yardwork done so I called Bob and he immediately helped me out.  I'd recommend him to all of my friends, even if they're still out on a cruise.</p>
							</div>
						</div>		
					</div>
				</div>	
				<div class="col-xs-6" id="secondColumn">
					<div class="col-xs-8">	
						<div class="panel panel-default">
							<div class="panel-body">
								<h6 id="reviews">Rachelle - Client since 2009</h6>
								<p>I called Bob after a crazy house party at my house which left the yard a mess.  He was there in 20 minutes and couldn't have done a better job.</p>
							</div>
						</div>
					</div>	
					<div class="col-xs-4">
						<img id="picOne" src="http://i.imgur.com/dnjTBGl.jpg">		
					</div>
				</div>		
		</div>
	</div>	
</div>

<!-- Contact Us Links -->
<div class="container contactUs">
	<div class="row">
		<h4>Contact Us</h4>
	</div>
	<div class="row" id="iconRow">
		<div class="col-xs-8">
			<div class="row">
				<div class="col-xs-3">
					  <a class="btn btn-social-icon btn-twitter" href="http://www.twitter.com">
		    			<i class="fa fa-twitter"> Twitter</i>
		  			  </a>	
				</div>
				<div class="col-xs-3">
					  <a class="btn btn-social-icon btn-google-plus" href="http://www.google.com">
		    			<i class="fa fa-google-plus"> Google Plus</i>
		  			  </a>				
				</div>	
				<div class="col-xs-3">
					  <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com">
		    			<i class="fa fa-facebook"> Facebook</i>
		  			  </a>				
				</div>	
				<div class="col-xs-3">
					  <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com">
		    			<i class="fa fa-linkedin"> LinkedIn</i>
		  			  </a>				
				</div>	
			</div>	
			<div class="row">
				<div>
				Palm Landscaping Services originated in 1997 in Las Vegas, NV.  Bob Palmer founded the company after realizing how many people were in need of great landscaping services in the Las Vegas suburbs.  Deliving great work on top of solid customer service is our #1 priority for you, the customer.  Feel free to reach out to us on our Social Media sites found above.</div><br>
				<div>You can find us at :</div>
				<div>123 Anywhere Street</div>
				<div>Las Vegas, NV 12345</div>
			</div>
		</div>	

<!-- Google Map -->
		<div class="col-xs-4">
			<div style='width: 100px;'>
  				<div id="map" style='width: 400px; height: 300px;'></div>
			</div>
		</div>	
		<script type="text/javascript">
			handler = Gmaps.build('Google');
			handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
			  markers = handler.addMarkers([
			    {
			      "lat": 36.084205,
			      "lng": -115.286834,
			      "picture": {
			        "width":  36,
			        "height": 36
			      },
			      "infowindow": "hello!"
			    }
			  ]);
			  handler.bounds.extendWith(markers);
			  handler.fitMapToBounds();
			});
		</script>


	</div>	

</div>
</body>

app/views/users/show.html.erb
<script src="../app/assets/javascripts/application.js"></script>
<%= render partial: "users/navbar" %>	

<!-- Current Jobs -->
<div class="container" id="currentJobsDiv">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-default">
			  <div class="panel-body">
    			<h4>Current Job</h4>
    				<div class="panel panel-default">
			  			<div class="panel-body">
			    			<TABLE>
							   <TR>
							      <TH>Job Site Location</TH>
							      <TH>Time In</TH>
							      <TH>Time Out<TH>
							      <TH>Upload Image</TH>
							   </TR>
							   <TR>
							      <TD id="vegasStrip">Las Vegas Strip</TD>
							      <TD><button id="timeInOne">Time In</button></TD>
							      <TD><button id="timeOutOne">Time Out</button></TD>
							      <TD><button id="imageBtn">Image</button></TD>
							   </TR>
							</TABLE>
						</div>
			    			<TABLE id="secondTable">
							   <TR>
							      <TH>Date</TH>
							      <TH>Time In</TH>
							      <TH>Time Out<TH>
							   </TR>
							   <TR>
							      <TD class="clearTime">Wed Jul 1 2015</TD>
							      <TD class="clearTime">6:49am</TD>
							      <TD class="clearTime">7:13pm</TD>
							   </TR>
							   <TR>
							      <TD class="clearTime">Thur July 2 2015</TD>
							      <TD class="clearTime">7:05am</TD>
							      <TD class="clearTime">6:29pm</TD>
							   </TR>
							   <TR>
							      <TD id="currentDate"></TD>
							      <TD id="timeIn"></TD>
							      <TD id="timeOut"></TD>
							   </TR>							   							   
							</TABLE>						
					</div>		
    			<button class="btn" id="jobComp">Job Complete</button>
  			  </div>  			  
			</div>
		<div>	
	</div>
</div>	









<!-- Past Jobs -->
<div class="container" id="pastJobs">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-default">
			  <div class="panel-body">
    			<h4>Past Jobs</h4>
    				<div class="panel panel-default">
			  			<div class="panel-body">
			    			<TABLE>
							   <TR>
							      <TH id="location">Job Site Location</TH>
							      <TH>Time In</TH>
							      <TH>Time Out</TH>
							      <TH>Images</TH>
							   </TR>
							   <TR>
							      <TD id="scHouse">Spencer Cornelia's House</TD>
							      <TD>8:32am</TD>
							      <TD>5:15pm</TD>
							      <TD><button id="button1">Images</button></TD>
							   </TR>
							   <TR>
							      <TD>Thomas Co.</TD>
							      <TD>6:37am</TD>
							      <TD>5:45pm</TD>
							      <TD><button id="button2">Images</button></TD>
							   </TR>
							   <TR>
							      <TD id="vegasStrip2"></TD>
							      <TD></TD>
							      <TD></TD>
							      <TD><button id="button3">Images</button></TD>
							   </TR>							   
							</TABLE>
						</div>
					</div>	    			
  			  </div>
			</div>
		<div>	
	</div>
</div>	


<!-- Pictures of jobs -->
<div class="container" id="allPictures1">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-default">
			  <div class="panel-body">
			  	<div class="row">
			  		<div class="col-xs-12">
						<img src="http://i.imgur.com/znbdZse.jpg">
						<img src="http://i.imgur.com/xxsK6Ch.jpg">
						<img src="http://i.imgur.com/airy542.jpg">
						<img src="http://i.imgur.com/X0gsu4v.jpg">
						<img src="http://i.imgur.com/BXIq4Y5.jpg">
  			    	</div>
  			    </div>
  			    <div class="row">
  			    	<div class="col-xs-2">
  			    		<button class="btn" id="hideBtn">Hide</button>  			    		    
  			  		</div>
  			  	</div>  			    			    
  			  </div>
			</div>
		<div>	
	</div>
</div>	

<div class="container" id="allPictures2">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-default">
			  <div class="panel-body">
			  	<div class="row">
			  		<div class="col-xs-12">
						<img src="http://i.imgur.com/O0rnGrb.jpg">
						<img src="http://i.imgur.com/8E8rj8S.jpg">
						<img src="http://i.imgur.com/airy542.jpg">
						<img src="http://i.imgur.com/X0gsu4v.jpg">
						<img src="http://i.imgur.com/BXIq4Y5.jpg">
  			    	</div>
  			    </div>	
  			    <div class="row">
  			    	<div class="col-xs-2">
  			    		<button class="btn" id="hideBtn2">Hide</button>  			    		    
  			  		</div>
  			  	</div>
  			  </div>
			</div>
		<div>	
	</div>
</div>